server {
    listen 8080;

    client_max_body_size 1M;

    error_page 404 /errors/404.html;
    error_page 500 /errors/500.html;

    # Python CGI — guestbook.py shebang ile doğrudan çalışır
    location /python {
        root cgi-site/python;
        index guestbook.py;
        methods GET POST;
        cgi_extension .py;
    }

    # Go CGI — gorun ile çalıştırma
    # gorun kurulu ise guestbook.go dosyasındaki shebang (#!/usr/bin/env gorun) devreye girer
    location /go {
        root cgi-site/go;
        index guestbook.go;
        methods GET POST;
        cgi_extension .go;
    }
}
