server {
	listen 8080;
	root /Users/nothing/cowd/webserv/www;
	index index.html;
	autoindex on;
	methods GET POST;

	location /upload {
		methods POST;
		upload_store /Users/nothing/cowd/webserv/www/uploads;
	}

	location /cgi-bin {
		index echo.sh;
		methods GET POST;
		cgi_extension .sh;
	}
}
