server {
	listen 8080;
	root /Users/nothing/cowd/webserv/www;
	index index.html;
	autoindex on;

	location /upload {
		methods POST;
		upload_store /Users/nothing/cowd/webserv/www/uploads;
	}

	location /cgi-bin {
		methods GET POST;
		cgi_extension .sh;
	}


}