server {
	listen 127.0.0.1:8080;
	listen 127.0.0.1:65535;

	root /home/ahekinci/code/webserv/www;

	error_page 404 /errors/404.html;
	error_page 500 /errors/500.html;

	location / {
		autoindex on;
		error_page 403 /errors/403.html;
	}

	location /static {
		autoindex on;
		error_page 403 /errors/403.html;
	}

	location /uploads {
		methods GET POST DELETE;
		autoindex on;
		upload_store /home/ahekinci/code/webserv/www/uploads;
	}

	location /cgi-bin {
		methods GET POST;
		autoindex on;
		cgi_extension .sh;
		cgi_extension .py;
	}

	location /redirect {
		redirect 301 /;
	}
}

# chat server
server {
	listen 8081;

	methods GET POST;

	location / {
		root /home/ahekinci/code/webserv/www/cgi-bin;
		index chat.py;
		cgi_extension .py;
	}
}
