server {
	listen 8080;
	root /home/ahekinci/code/webserv/www;
	index index.html;
	autoindex on;
	methods GET POST;

	location /upload {
		methods POST;
		upload_store /home/ahekinci/code/webserv/www/uploads;
	}

	location /cgi-bin {
		index echo.sh;
		methods GET POST;
		cgi_extension .sh;
	}

	location /old {
		redirect 301 /;
	}
}